### ISSUE TITLE
hello friend

### ISSUE THREAD

**Issue by Tomlk** [tiancity-NJU/da-faster-rcnn-PyTorch#22]
when I try training , there is a permissionError,

new: /data/ztc/adaptation/Experiment/da_model/vgg16/cityscape
Traceback (most recent call last):
  File "da_trainval_net.py", line 229, in <module>
    os.makedirs(output_dir)
  File "/home/lk/anaconda3/envs/envp/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/lk/anaconda3/envs/envp/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/lk/anaconda3/envs/envp/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 3 more times]
  File "/home/lk/anaconda3/envs/envp/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data'

I have made dir "cityspace" in "/da-faster-rcnn-Pytorch-master/data" and made vgg16_caffe.pth in "/da-faster-rcnn-Pytorch-master"

**Comment by tiancity-NJU** [comment]
./data is relative path and /data is absolute path. The reason maybe you do not access to root path /data
