### ISSUE TITLE
when batchsize>1,it get errors.

### ISSUE THREAD

**Issue by huihuiustc** [tiancity-NJU/da-faster-rcnn-PyTorch#4]

**Comment by huihuiustc** [comment]
好像是图像的尺寸不一样，我们是不是应该补齐图像到同样的尺寸？

**Comment by tiancity-NJU** [comment]
can you provide the error log when you run ?  I think you could try print the size of batch image before entering the network and find the error

**Comment by stormchasingg** [comment]
when batchsize > 1 or using --mGPUs flag, it gets error  
`Traceback (most recent call last):
  File "da_trainval_net.py", line 411, in <module>
    tgt_im_data, tgt_im_info, tgt_gt_boxes, tgt_num_boxes, tgt_need_backprop)
  File "/root/.pyenv/versions/dl_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/dl_pytorch/da-faster-rcnn-PyTorch/lib/model/da_faster_rcnn/faster_rcnn.py", line 50, in forward
    assert need_backprop.detach() == 1 and tgt_need_backprop.detach() == 0
RuntimeError: bool value of Tensor with more than one value is ambiguous`
then i changed the code  
`assert all(need_backprop.detach()) == 1 and all(tgt_need_backprop.detach()) == 0`
it gets another error  
`Traceback (most recent call last):
  File "da_trainval_net.py", line 411, in <module>
    tgt_im_data, tgt_im_info, tgt_gt_boxes, tgt_num_boxes, tgt_need_backprop)
  File "/root/.pyenv/versions/dl_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/.pyenv/versions/dl_pytorch/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 115, in forward
    return self.gather(outputs, self.output_device)
  File "/root/.pyenv/versions/dl_pytorch/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 127, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/root/.pyenv/versions/dl_pytorch/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    return gather_map(outputs)
  File "/root/.pyenv/versions/dl_pytorch/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/root/.pyenv/versions/dl_pytorch/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 55, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/root/.pyenv/versions/dl_pytorch/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 54, in forward
    ctx.input_sizes = tuple(map(lambda i: i.size(ctx.dim), inputs))
  File "/root/.pyenv/versions/dl_pytorch/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 54, in <lambda>
    ctx.input_sizes = tuple(map(lambda i: i.size(ctx.dim), inputs))
RuntimeError: dimension specified as 0 but tensor has no dimensions`
it seems that the code is not ready for a multiple GPUs operation, how could i fix it?

**Comment by stormchasingg** [comment]
and i add DA loss for mGPUs in da_trainval_net.py line 414
[https://github.com/tiancity-NJU/da-faster-rcnn-PyTorch/blob/f4b6ac4f16159b1b6416bb96bfd57e6e0ba7cdbe/da_trainval_net.py#L414](url)
